### PR TITLE
Log exceptions to the DeployEvent log

### LINKED ISSUE #115: Show cf api errors in the web view
Currently the only way to discover why a deploy failed is to run `cf logs qafire-sidekiq` or, if your fast enough, look at `/queue` at the retries. We should log an error using the DeployEventService so the user can at least know where to start looking.

### PR DESCRIPTION
**Pull request by tessereth**
This will cause failures to appear on a deploy#show page. I've manually tested it and it works but I couldn't figure out how to test it in rspec. Also I'm assuming there are never any secrets in an exception message. 

fixes #115

image

### CODE REVIEW

File: app/services/deploy_event_service.rb [hunk 1]
```diff
@@ -48,6 +48,14 @@ def service_already_exists!
     save_event("A service has been reused as it already existed")
   end
 
+  def unexpected_error!(error)
+    if error.is_a?(RestClient::ExceptionWithResponse)
+      save_event("#{error.class}: #{error}, Body: #{error.response}")
```
Comment (micapam) [inline app/services/deploy_event_service.rb]: These are stored in the DB right? Is there any limit on the length of the messages?

**Review by micapam — APPROVED** [review]
So long as messages can be saved regardless of length (as per my comment), this LGTM. 

Re rspec: It might be possible to add a spec but you would basically end up mocking everything under the sun to no good purpose - so I agree it's not worth a spec.

File: app/services/deploy_event_service.rb (hunk 1 above)
Comment (tessereth) [inline app/services/deploy_event_service.rb]:
```
                                     Table "public.deploy_events"
   Column   |            Type             |                         Modifiers
------------+-----------------------------+------------------------------------------------------------
 id         | integer                     | not null default nextval('deploy_events_id_seq'::regclass)
 timestamp  | timestamp without time zone |
 message    | character varying           |
 deploy_id  | integer                     |
 created_at | timestamp without time zone | not null
 updated_at | timestamp without time zone | not null
```
I'm guessing that means no message length limit.
